image: php:7.4-fpm

definitions:
  caches:
    vendor-directory: vendor
  steps:
    # - step: &install-php-extensions
    #     name: Install PHP Extensions
    #     script:
    #       # Installing first the libraries necessary to configure and install gd
    #       - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
    #       # Now we can configure and install the extension
    #       - docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/
    #       - docker-php-ext-install -j$(nproc) gd
    - step: &install-composer
        name: Install dependencies
        artifacts:
          - "vendor/**"
        caches:
          - composer # See https://confluence.atlassian.com/bitbucket/caching-dependencies-895552876.html
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs --optimize-autoloader
      services:
        - docker
    - step: &run-tests
        name: Run the tests
        script:
          - ./vendor/bin/phpunit --testsuite "Unit Test Suite"
        services:
          - docker

pipelines:
  branches:
    "{master,develop}":
      # - step: *install-php-extensions
      - step: *install-composer
      - step: *run-tests
  custom:
    manually:
      # - step: *install-php-extensions
      - step: *install-composer
      - step: *run-tests
  pull-requests:
    '**':
      # - step: *install-php-extensions
      - step: *install-composer
      - step: *run-tests
